POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Agegeg",
    "author": "Kevin eDavid",
    "url": "https://www.hrzhrz.fr",
    "likes": 32,
    "userId": "618258dfeaf83c6f3b5ebec4"
}