POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsemEiLCJpZCI6IjYxODI4ZGI5MThiMDIxZjUzNmY5ODg3YiIsImlhdCI6MTYzNTk0NTk5MX0.u3CNYwglh0molgDJ753_T9hojVivV2lRt5SVkGzVzHk

{
    "title": "Test after tokens 6",
    "author": "Kevin Token 6",
    "url": "https://www.hrzhrz-token.co.uk",
    "likes": 1,
    "userId": "61829192ba677a02c125c474"
}